/**
 * Build the Uniswap V4 pool registry for Robinhood Chain.
 *
 * V4 pools cannot be discovered the way V2 and V3 pools are. There is no
 * factory with a getPool(a, b, fee), and fee and tick spacing are free
 * parameters, so guessing keys misses most of the liquidity. The PoolManager
 * does emit an Initialize event for every pool it creates, with both
 * currencies indexed, so the pools between tokens this router lists can be
 * read straight out of the logs.
 *
 * Kept: pools with no hooks, between two listed tokens (native ETH counts as
 * WETH), holding liquidity right now. At most POOLS_PER_PAIR per pair, the
 * deepest first. Almost every V4 pool on the chain is a launchpad token nobody
 * trades; filtering by currency in the log query means they are never fetched.
 *
 *   npm run scan:v4
 */

import { writeFileSync } from 'node:fs';
import { parseAbi, parseAbiItem, getAddress, type Address } from 'viem';
import { CHAINS, type V4PoolKey } from '../src/lib/chain';
import { client } from '../src/lib/quote';

const POOLS_PER_PAIR = 3;
const NATIVE = '0x0000000000000000000000000000000000000000';
const OUT = new URL('../src/lib/v4-pools.ts', import.meta.url);

const chain = CHAINS.robinhood;
const v4 = chain.v4!;
const c = client(chain);

const initialize = parseAbiItem(
  'event Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, uint24 fee, int24 tickSpacing, address hooks, uint160 sqrtPriceX96, int24 tick)',
);
const stateView = parseAbi(['function getLiquidity(bytes32 poolId) view returns (uint128)']);

const listed = [NATIVE as Address, ...chain.tokens.map((t) => t.address)];
const asset = (a: string) => (a.toLowerCase() === NATIVE ? chain.weth.address.toLowerCase() : a.toLowerCase());

async function scan() {
  const head = await c.getBlockNumber();
  const found: { id: `0x${string}`; key: V4PoolKey }[] = [];
  let from = 0n;
  let step = 8_000_000n;
  while (from <= head) {
    const to = from + step > head ? head : from + step;
    try {
      const logs = await c.getLogs({
        address: v4.poolManager,
        event: initialize,
        args: { currency0: listed, currency1: listed },
        fromBlock: from,
        toBlock: to,
      });
      for (const l of logs) {
        const a = l.args;
        if (a.hooks !== NATIVE) continue;
        found.push({
          id: a.id!,
          key: {
            currency0: getAddress(a.currency0!),
            currency1: getAddress(a.currency1!),
            fee: a.fee!,
            tickSpacing: a.tickSpacing!,
            hooks: NATIVE,
          },
        });
      }
      from = to + 1n;
    } catch {
      // The endpoint caps the range a log query may cover. Halve and retry.
      step /= 2n;
      if (step < 10_000n) throw new Error(`log query keeps failing at block ${from}`);
    }
  }
  return found;
}

const found = (await scan()).filter((p) => asset(p.key.currency0) !== asset(p.key.currency1));
console.log(`${found.length} hookless pools between listed tokens`);

const liquidity = await c.multicall({
  contracts: found.map((p) => ({
    address: v4.stateView,
    abi: stateView,
    functionName: 'getLiquidity' as const,
    args: [p.id] as const,
  })),
  allowFailure: true,
  // A few large aggregate calls rather than dozens of small ones, which this
  // endpoint rejects when they arrive together in one JSON-RPC batch.
  batchSize: 64_000,
});

// Raw liquidity is only comparable between pools of the same pair, which is
// the only comparison made with it.
const byPair = new Map<string, { key: V4PoolKey; L: bigint }[]>();
found.forEach((p, i) => {
  const r = liquidity[i];
  const L = r.status === 'success' ? (r.result as bigint) : 0n;
  if (L === 0n) return;
  const pair = [asset(p.key.currency0), asset(p.key.currency1)].sort().join(':');
  const list = byPair.get(pair) ?? [];
  list.push({ key: p.key, L });
  byPair.set(pair, list);
});

const kept: V4PoolKey[] = [];
for (const list of byPair.values()) {
  list.sort((a, b) => (a.L > b.L ? -1 : 1));
  kept.push(...list.slice(0, POOLS_PER_PAIR).map((x) => x.key));
}
const symbol = (a: string) =>
  a === NATIVE ? 'ETH' : chain.tokens.find((t) => t.address.toLowerCase() === a.toLowerCase())!.symbol;
kept.sort((a, b) =>
  `${symbol(a.currency0)}/${symbol(a.currency1)}`.localeCompare(`${symbol(b.currency0)}/${symbol(b.currency1)}`),
);

const lines = kept.map(
  (k) =>
    `  // ${symbol(k.currency0)}/${symbol(k.currency1)} ${(k.fee / 10_000).toFixed(4)}%\n` +
    `  { currency0: '${k.currency0}', currency1: '${k.currency1}', fee: ${k.fee}, tickSpacing: ${k.tickSpacing}, hooks: '${NATIVE}' },`,
);

writeFileSync(
  OUT,
  `// Generated by scripts/scan-v4.ts — do not edit by hand.
import type { V4PoolKey } from './chain';

export const ROBINHOOD_V4_POOLS: readonly V4PoolKey[] = [
${lines.join('\n')}
];
`,
);
console.log(`${kept.length} pools across ${byPair.size} pairs written to src/lib/v4-pools.ts`);
